### ISSUE TITLE
[BUG][Registry] Podman-BootC doesn't connect to local registry

### ISSUE THREAD

**Issue by tmichett** [tmichett/Fedora_BootC#2]
podman-bootc not respecting local registry configuration and attempts to connect via HTTPS and on port 443

**Comment by tmichett** [comment]
Doesn't like localhost at all so need to start a registry and tag/push


`podman run -d --name registry -p 5000:5000 --restart=always docker.io/library/registry:2
`

Testing Registry

`curl -v http://localhost:5000/v2/
`

```
 >podman info --debug | grep -A5 "registries"
registries:
  localhost:5000:
    Blocked: false
    Insecure: true
    Location: localhost:5000
    MirrorByDigestOnly: false
```
```

 >curl -s http://localhost:5000/v2/_catalog | jq
{
  "repositories": [
    "fedora_bootc"
  ]
}
```



```
unqualified-search-registries = ["docker.io"]

[[registry]]
location = "localhost:5000"
insecure = true

[[registry]]
location = "http://localhost:5000"
insecure = true
```

```
podman save -o fedora_bootc.tar localhost:5000/fedora_bootc

podman-bootc run --filesystem=xfs fedora_bootc
```
